services:
  nginx:
    build:
      context: deploy/
    restart: unless-stopped
    volumes_from:
      - web
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app
  web:
    image: ${WEB_IMAGE}
    build:
      context: .
    restart: unless-stopped
    volumes:
      - static:/app/public
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  static:
